---
name: Release

'on':
  push:
    tags:
      - '*'

defaults:
  run:
    working-directory: gepaplexx.tftp

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          path: gepaplexx.tftp

      - name: Create Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: ${{ github.ref }}
          body: ''
          draft: false
          prerelease: false

      - name: Set up Python 3
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: Install Ansible
        run: pip3 install ansible-base

      - name: Trigger a new import on Galaxy
        run: >
              ansible-galaxy role import
              --token ${{ secrets.GALAXY_API_KEY }}
              $(echo ${{ github.repository }} | cut -d/ -f1)
              $(echo ${{ github.repository }} | cut -d/ -f2)
...
